{{ if and (or (eq .Values.database.type "mysql") (eq .Values.database.roundcubeType "mysql")) (not .Values.database.mysql.host) }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailu.fullname" . }}-mysql
  labels:
    {{- include "mailu.labels" . | nindent 4 }}    
    component: mysql
spec:
  selector:
    {{- include "mailu.selectorLabels" . | nindent 4 }}  
    component: mysql
  type: ClusterIP       
  ports:
  - name: mysql
    port: 3306
    protocol: TCP

{{ end }}
