{{- if .Values.ingress.enabled -}}
{{ if and (or (eq .Values.database.type "mysql") (eq .Values.database.roundcubeType "mysql")) (not .Values.database.mysql.host) }}
{{- $fullName := include "mailu.fullname" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}-mysql
  labels:
    component: mysql
    {{- include "mailu.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ include "mailu.fullname" . }}-mysql.{{ .Release.Namespace }}.svc.cluster.local
  gateways:
    # The reserved word mesh is used to imply all the sidecars in the mesh
    - mesh
  tcp:
  - match:
    - port: 3306
    route:
    - destination:
        host: {{ $fullName }}-mysql
        port:
          number: 3306

{{- end}}
{{- end}}
