{{ if .Capabilities.APIVersions.Has "apps/v1/Deployment" }}
apiVersion: apps/v1
{{ else }}
apiVersion: extensions/v1beta1
{{ end }}
kind: Deployment
metadata:
  name: {{ include "mailu.fullname" . }}-admin
spec:
  selector:
    matchLabels:
      {{- include "mailu.selectorLabels" . | nindent 6 }}  
      component: admin
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "mailu.labels" . | nindent 8 }}
        component: admin
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: admin
        image: {{ .Values.admin.image.repository }}:{{ default .Values.mailuVersion .Values.admin.image.tag }}
        imagePullPolicy: Always
        volumeMounts:
          - name: data
            subPath: admin
            mountPath: /data
          - name: data
            mountPath: /dkim
            subPath: dkim
        env:
          - name: LOG_LEVEL
            value: {{ default .Values.logLevel .Values.admin.logLevel }}
        envFrom:
          - configMapRef:
              name: mailu-config
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        {{- with .Values.admin.resources }}
        resources:
        {{- .|toYaml|nindent 10}}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /ui/login
            port: http
          periodSeconds: 10
          failureThreshold: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ui/login
            port: http
          periodSeconds: 10
          failureThreshold: 1
          timeoutSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "mailu.claimName" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
