apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailu.fullname" . }}-admin
  labels:
    {{- include "mailu.labels" . | nindent 4 }}    
    component: admin
spec:
  selector:
    {{- include "mailu.selectorLabels" . | nindent 4 }}  
    component: admin
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
