{{ if .Capabilities.APIVersions.Has "apps/v1/Deployment" }}
apiVersion: apps/v1
{{ else }}
apiVersion: extensions/v1beta1
{{ end }}
kind: Deployment
metadata:
  name: {{ include "mailu.fullname" . }}-rspamd
spec:
  selector:
    matchLabels:
      {{- include "mailu.selectorLabels" . | nindent 6 }}  
      component: rspamd
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "mailu.labels" . | nindent 8 }}  
        component: rspamd
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: rspamd
        image: {{ .Values.rspamd.image.repository }}:{{ default .Values.mailuVersion .Values.rspamd.image.tag }}
        imagePullPolicy: Always
        volumeMounts:
          - name: data
            subPath: rspamd
            mountPath: /var/lib/rspamd
          - name: data
            subPath: dkim
            mountPath: /dkim
        env:
          - name: LOG_LEVEL
            value: {{ default .Values.logLevel .Values.rspamd.logLevel }}
        envFrom:
          - configMapRef:
              name: mailu-config  
        ports:
          - name: rspamd
            containerPort: 11332
            protocol: TCP
          - name: rspamd-http
            containerPort: 11334
            protocol: TCP
        {{- with .Values.rspamd.resources }}
        resources:
        {{- .|toYaml|nindent 10}}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /
            port: rspamd-http
          periodSeconds: 5
          failureThreshold: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: rspamd-http
          periodSeconds: 10
          failureThreshold: 1
          timeoutSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "mailu.claimName" . }}