apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ include "mailu.fullname" . }}-rspamd-remote
  labels:
    {{- include "mailu.labels" . | nindent 4 }}    
    component: rspamd
spec:
  hosts:
      - "*.rspamd.com"
  ports:
      - number: 443
        name: https
        protocol: TLS
  resolution: NONE
  location: MESH_EXTERNAL
