{{- $fullName := include "mailu.fullname" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}-rspamd-internal
  labels:
    component: rspamd
    {{- include "mailu.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ include "mailu.fullname" . }}-rspamd.{{ .Release.Namespace }}.svc.cluster.local
  gateways:
    # The reserved word mesh is used to imply all the sidecars in the mesh
    - mesh           
  tcp:
  - match:
    - port: 11332
    route:
    - destination:
        host: {{ $fullName }}-rspamd
        port:
          number: 11332
  http:
  - name: tcp-rspamd-http
    match:
    - port: 11334
    route:
    - destination:
        host: {{ $fullName }}-rspamd
        port:
          number: 11334