# This file is derived from https://github.com/Mailu/Mailu/blob/master/docs/kubernetes/mailu/security.yaml
# (file is split into rspamd.yaml and clamav.yaml)

{{- if .Values.clamav.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailu.fullname" . }}-clamav
  labels:
    {{- include "mailu.labels" . | nindent 4 }}    
    component: clamav
spec:
  selector:
    {{- include "mailu.selectorLabels" . | nindent 4 }}  
    component: clamav
  type: ClusterIP   
  ports:
  - name: tcp-clamav
    port: 3310
    protocol: TCP

{{- end }}
