{{- if .Values.clamav.enabled }}
{{- $fullName := include "mailu.fullname" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}-clamav
  labels:
    component: clamav
    {{- include "mailu.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ include "mailu.fullname" . }}-clamav.{{ .Release.Namespace }}.svc.cluster.local
  gateways:
      # The reserved word mesh is used to imply all the sidecars in the mesh
    - mesh
  tcp:
  - match:
    - port: 3310
    route:
    - destination:
        host: {{ $fullName }}-clamav
        port:
          number: 3310

{{- end}}
