apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailu.fullname" . }}-front
  labels:
    {{- include "mailu.labels" . | nindent 4 }}    
    component: front
spec:
  selector:
    {{- include "mailu.selectorLabels" . | nindent 4 }}  
    component: front
  type: ClusterIP  
  ports:
  - name: pop3
    port: 110
    protocol: TCP
  - name: pop3s
    port: 995
    protocol: TCP
  - name: imap
    port: 143
    protocol: TCP
  - name: imaps
    port: 993
    protocol: TCP
  - name: smtp
    port: 25
    protocol: TCP
  - name: smtps
    port: 465
    protocol: TCP
  - name: smtpd
    port: 587
    protocol: TCP
  - name: smtp-auth
    port: 10025
    protocol: TCP
  - name: imap-auth
    port: 10143
    protocol: TCP
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: http-auth
    port: 8000
    protocol: TCP    
{{ if not .Values.ingress.externalIngress }}
  - name: https
    port: 443
    protocol: TCP
{{end}}
