apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailu.fullname" . }}-redis
  labels:
    {{- include "mailu.labels" . | nindent 4 }}    
    component: redis
spec:
  selector:
    {{- include "mailu.selectorLabels" . | nindent 4 }}  
    component: redis
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    protocol: TCP
