{{- $clusterDomain := default "cluster.local" .Values.clusterDomain}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mailu.fullname" . }}-config
  labels:
  {{- include "mailu.labels" . | nindent 4 }}
data:
    # Mailu main configuration file
    #
    # Most configuration variables can be modified through the Web interface,
    # these few settings must however be configured before starting the mail
    # server and require a restart upon change.

    ###################################
    # Common configuration variables
    ###################################

    # Set to a randomly generated 16 bytes string
    SECRET_KEY: "{{ required "secretKey" .Values.secretKey }}"

    # Main mail domain
    DOMAIN: "{{ required "domain" .Values.domain }}"

    # Hostnames for this server, separated with comas
    HOSTNAMES: "{{ join "," .Values.hostnames }}"

    # Postmaster local part (will append the main mail domain)
    POSTMASTER: {{ .Values.postmaster }}

    # Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
    TLS_FLAVOR: {{ .Values.ingress.tlsFlavor }}

    # Authentication rate limit (per source IP address)
    AUTH_RATELIMIT: "{{ required "mail.authRatelimit" .Values.mail.authRatelimit }}"

    # Opt-out of statistics, replace with "True" to opt out
    DISABLE_STATISTICS: "False"

    ###################################
    # Kubernetes configuration
    ###################################

    # Use Kubernetes Ingress Controller to handle all actions on port 80 and 443
    # This way we can make use of the advantages of the cert-manager deployment
    KUBERNETES_INGRESS: "{{ .Values.ingress.externalIngress }}"

    SUBNET: {{ .Values.subnet }}
    # POD_ADDRESS_RANGE is normally provided by default with Kubernetes
    # Only use this value when you are using Flannel, Calico or a special kind of CNI
    # Provide the IPs of your network interface or bridge which is used for VXLAN network traffic
    POD_ADDRESS_RANGE: {{ .Values.podSubnet }}

    ###################################
    # Optional features
    ###################################

    # Expose the admin interface (value: true, false)
    ADMIN: "true"
    # Run the admin interface in debug mode
    #DEBUG: "True"

    # Choose which webmail to run if any (values: roundcube, rainloop, none)
    WEBMAIL: "roundcube"

    # Dav server implementation (value: radicale, none)
    {{- if .Values.webdav.enabled }}
    WEBDAV: "radicale"    
    {{- else }}
    WEBDAV: "none"
    {{- end }}
    WEBDAV_ADDRESS: {{ include "mailu.fullname" . }}-webdav.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}:5232
    HOST_WEBDAV: {{ include "mailu.fullname" . }}-webdav.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}:5232

    # Antivirus solution (value: clamav, none)
    {{- if .Values.clamav.enabled }}
    ANTIVIRUS: "clamav"
    ANTIVIRUS_ADDRESS: {{ include "mailu.fullname" . }}-clamav.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}:3310
    HOST_ANTIVIRUS: {{ include "mailu.fullname" . }}-clamav.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}:3310
    {{- else }}
    ANTIVIRUS: "none"
    ANTIVIRUS_ADDRESS: "localhost"
    HOST_ANTIVIRUS: "localhost"
    {{- end }}
    ###################################
    # Mail settings
    ###################################

    # Message size limit in bytes
    # Default: accept messages up to 50MB
    MESSAGE_SIZE_LIMIT: "{{ mul .Values.mail.messageSizeLimitInMegabytes (mul 1024 1024) }}"

    # Will relay all outgoing mails if configured
    #RELAYHOST=

    # This part is needed for the XCLIENT login for postfix. This should be the POD ADDRESS range
    FRONT_ADDRESS: {{ include "mailu.fullname" . }}-front.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}

    ADMIN_ADDRESS: {{ include "mailu.fullname" . }}-admin.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}
    HOST_ADMIN: {{ include "mailu.fullname" . }}-admin.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}


    ANTISPAM_WEBUI_ADDRESS: {{ include "mailu.fullname" . }}-rspamd.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}:11334
    HOST_ANTISPAM_WEBUI: {{ include "mailu.fullname" . }}-rspamd.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}:11334
    ANTISPAM_MILTER_ADDRESS: {{ include "mailu.fullname" . }}-rspamd.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}:11332
    HOST_ANTISPAM_MILTER: {{ include "mailu.fullname" . }}-rspamd.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}:11332

    # This value  is needed by the webmail to find the correct imap backend
    IMAP_ADDRESS: {{ include "mailu.fullname" . }}-dovecot.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}
    HOST_IMAP: {{ include "mailu.fullname" . }}-dovecot.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}

    # This value is used by Dovecot to find the Redis server in the cluster
    REDIS_ADDRESS: {{ include "mailu.fullname" . }}-redis.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}
    HOST_REDIS: {{ include "mailu.fullname" . }}-redis.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}

    POP3_ADDRESS: {{ include "mailu.fullname" . }}-dovecot.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}
    HOST_POP3: {{ include "mailu.fullname" . }}-dovecot.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}

    # SMTP
    SMTP_ADDRESS: {{ include "mailu.fullname" . }}-postfix.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}
    HOST_SMTP: {{ include "mailu.fullname" . }}-postfix.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}

    AUTHSMTP_ADDRESS: {{ include "mailu.fullname" . }}-postfix.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}
    HOST_AUTHSMTP: {{ include "mailu.fullname" . }}-postfix.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}

    LMTP_ADDRESS:  {{ include "mailu.fullname" . }}-dovecot.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}:2525
    # Fetchmail delay
    FETCHMAIL_DELAY: "600"

    # Recipient delimiter, character used to delimiter localpart from custom address part
    # e.g. localpart+custom@domain;tld
    RECIPIENT_DELIMITER: "+"

    REJECT_UNLISTED_RECIPIENT: "yes"

    # DMARC rua and ruf email
    DMARC_RUA: {{ .Values.postmaster }}
    DMARC_RUF: {{ .Values.postmaster }}

    # Welcome email, enable and set a topic and body if you wish to send welcome
    # emails to all users.
    WELCOME: "false"
    WELCOME_SUBJECT: "Welcome to your new email account., test"
    WELCOME_BODY: "Welcome to your new email account, if you can read this, then it is configured properly!"

    ###################################
    # Web settings
    ###################################

    {{- if .Values.roundcube.enabled }}
    WEBMAIL:  roundcube
    WEBMAIL_ADDRESS: {{ include "mailu.fullname" . }}-roundcube.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}
    HOST_WEBMAIL: {{ include "mailu.fullname" . }}-roundcube.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}
    {{- else }}
    WEBMAIL:  none
    WEBMAIL_ADDRESS: localhost
    HOST_WEBMAIL: localhost
    {{- end }}
    # Path to the admin interface if enabled
    # Kubernetes addition: You need to change ALL the ingresses, when you want this URL to be different!!!
    # WEB_ADMIN: {{ .Values.admin.url }} 

    # Path to the webmail if enabled
    # Currently, this is not used, because we intended to use a different subdomain: webmail.example.com
    # This option can be added in a feature release
    WEB_WEBMAIL: {{ .Values.webmail.url }} 

    # Website name
    SITENAME: "Mailu"

    # Linked Website URL
    WEBSITE: "https://{{ required "domain" .Values.domain  }}"

    # Registration reCaptcha settings (warning, this has some privacy impact)
    # RECAPTCHA_PUBLIC_KEY=
    # RECAPTCHA_PRIVATE_KEY=

    # Domain registration, uncomment to enable
    # DOMAIN_REGISTRATION=true

    ###################################
    # Advanced settings
    ###################################

    # Create an admin account if it does not exist yet. It will also create the email domain for the account.
    {{- if .Values.initialAccount }}
    INITIAL_ADMIN_ACCOUNT: {{ required "initialAccount.username" .Values.initialAccount.username }}
    INITIAL_ADMIN_DOMAIN: {{ required "initialAccount.domain" .Values.initialAccount.domain }}
    INITIAL_ADMIN_PW: {{ required "initialAccount.password" .Values.initialAccount.password }}
    {{- end }}
    # Docker-compose project name, this will prepended to containers names.
    COMPOSE_PROJECT_NAME: "mailu"

    # Default password scheme used for newly created accounts and changed passwords
    # (value: SHA512-CRYPT, SHA256-CRYPT, MD5-CRYPT, CRYPT)
    PASSWORD_SCHEME: "{{ default "PBKDF2" .Values.passwordScheme }}"

    # Header to take the real ip from
    #REAL_IP_HEADER:

    # IPs for nginx set_real_ip_from (CIDR list separated by commas)
    #REAL_IP_FROM:

    
    QUOTA_STORAGE_URL: redis://{{ include "mailu.fullname" . }}-redis/1
    RATELIMIT_STORAGE_URL: redis://{{ include "mailu.fullname" . }}-redis/2


    DB_FLAVOR: {{ .Values.database.type }}
    {{- if eq .Values.database.type "mysql" }}
    DB_USER: {{ required "database.mysql.user" .Values.database.mysql.user }}
    DB_PW: {{ required "database.mysql.password" .Values.database.mysql.password }}
    DB_NAME: {{ required "database.mysql.database" .Values.database.mysql.database }}
    {{- if .Values.database.mysql.host }}
    DB_HOST: {{ .Values.database.mysql.host }}
    {{- else }}
    DB_HOST:  {{ include "mailu.fullname" . }}-mysql.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}
    {{- end }}
    {{- end }}


    {{- if eq .Values.database.roundcubeType "sqlite" }}
    ROUNDCUBE_DB_FLAVOR: sqlite
    {{- else if eq .Values.database.roundcubeType "mysql" }}
    ROUNDCUBE_DB_USER: {{ required "database.mysql.roundcubeUser" .Values.database.mysql.roundcubeUser }}
    ROUNDCUBE_DB_PW: {{ required "database.mysql.roundcubePassword" .Values.database.mysql.roundcubePassword }}
    ROUNDCUBE_DB_NAME: {{ required "database.mysql.roundcubeDatabase" .Values.database.mysql.roundcubeDatabase }}
    {{- if .Values.database.mysql.host }}
        {{- if .Values.database.mysql.host }}
    ROUNDCUBE_DB_HOST: {{ .Values.database.mysql.host }}
        {{- end }}
    ROUNDCUBE_DB_HOST: {{ include "mailu.fullname" . }}-mysql.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}
    {{- end }}
    {{- end }}